name: release apk

on:
  push:
    branches:
      - main

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
      #      - name: Build APK
      #        run: bash ./gradlew assembleDebug --stacktrace
      - name: Generate Keystore file from Github Secrets
        run: |
          echo "$" > ./keystore.b64
          base64 -d -i ./keystore.b64 > ./$
          cp ./$ ./app/$
      - name: Build Signed APK
        run: |
          bash ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file=$ \
            -Pandroid.injected.signing.store.password=$ \
            -Pandroid.injected.signing.key.alias=$ \
            -Pandroid.injected.signing.key.password=$ \
            --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
  release:
    permissions: write-all
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: set now
        run: |
          echo "now=v$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: $
        with:
          tag_name: $
          release_name: Release $
      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: $
        with:
          upload_url: $
          asset_path: apk/app-release.apk
          asset_name: $.apk
          asset_content_type: application/zip
